iwatch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('myapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('movie_list', views.MovieView.as_view(), name='movie_list'),
    path('filter/', views.FilterMoviesView.as_view(), name='movie_filter'),
    path('search/', views.Search.as_view(), name='search'),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
    path('actor/<slug:slug>/', views.ActorDetailView.as_view(), name='actor_detail'),
]

myapp/models.py
from django.utils.text import slugify
from django.db import models
from datetime import date, datetime

from django.urls import reverse


class Category(models.Model):
    """Categoriile de filme"""

    name = models.CharField("Category", max_length=50)
    description = models.TextField('Description')
    url = models.SlugField(max_length=100, unique=True, default=name)

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField('Name', max_length=100)
    birth = models.DateField('Date of Birth')
    description = models.TextField('Description')
    img = models.ImageField('Image', upload_to='actors/')
    url = models.SlugField(max_length=100, unique=True, default='', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        value = self.name
        self.url = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Genre(models.Model):
    name = models.CharField("Genre", max_length=50)
    description = models.TextField('Description')
    url = models.SlugField(max_length=100, unique=True, default='', blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        value = self.name
        self.url = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class Movie(models.Model):
    title = models.CharField('Title', max_length=100)
    tagline = models.CharField('Tagline', max_length=100, default='')
    description = models.TextField('Description')
    poster = models.ImageField('Image', upload_to='movie/')
    year = models.IntegerField('Year', default='')
    country = models.CharField('Conuntry', max_length=50)
    directors = models.ManyToManyField(Actor, verbose_name='Director', related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='Actors', related_name='film_actor')
    genres = models.ManyToManyField(Genre, verbose_name='Genres')
    imdb_ratting = models.FloatField('iMDb Ratting', default=5)
    world_premiere = models.DateField('World Premiere', default=date.today)
    budget = models.PositiveIntegerField('Budget', default=0, help_text='Indicate in $')
    fees_in_usa = models.PositiveIntegerField('Fees in USA', default=0, help_text='Indicate in $')
    fees_in_world= models.PositiveIntegerField('Fees in world', default=0, help_text='Indicate in $')
    category = models.ForeignKey(Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
    trailer = models.CharField('Trailer', max_length=200, default='')
    url = models.SlugField(max_length=100, unique=True, blank=True, default='')
    draft = models.BooleanField('Draft', default=False)

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={"slug": self.url})

    def save(self, *args, **kwargs):
        value = self.title
        self.url = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class MovieShots(models.Model):
    title = models.CharField('Title', max_length=100)
    description = models.TextField('Description')
    image = models.ImageField('Image', upload_to='movies_shot/')
    movies = models.ForeignKey(Movie, verbose_name='Movie', on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class RattingStar(models.Model):
    value = models.SmallIntegerField('Value', default=0)

    def __str__(self):
        return self.value


class Ratting(models.Model):
    ip = models.CharField('IP adress', max_length=15)
    star = models.ForeignKey(RattingStar, on_delete=models.CASCADE, verbose_name='star')
    movie = models.ForeignKey(Movie, verbose_name='Movie', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.star} - {self.movie}"


class Reviews(models.Model):

    email = models.EmailField()
    name = models.CharField("Name", max_length=100)
    text = models.TextField('Description')
    date = models.DateTimeField(default=datetime.now, editable=False)
    parent = models.ForeignKey('self', verbose_name='Parent', on_delete=models.SET_NULL, blank=True, null=True)
    movie = models.ForeignKey(Movie, verbose_name='Movie', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

myapp/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import Reviews, Ratting, RattingStar


class ReviewForm(forms.ModelForm):
    #Formular pentru adaugarea comentariilor
    captcha = ReCaptchaField()

    class Meta:
        model = Reviews
        fields = ("email", "name", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control", "placeholder": "Your name"}),
            "email": forms.EmailInput(attrs={"class": "form-control", "placeholder": "Your email"}),
            "text": forms.Textarea(attrs={"class": "form-control", "rows": "4", "placeholder": "Comment"})
        }


class RattingForm(forms.ModelForm):

    star = forms.ModelChoiceField(
        queryset=RattingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Ratting
        fields = ("star",)

myapp/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render,redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View, TemplateView

from .models import Movie, Category, Actor, Genre
from .forms import ReviewForm, RattingForm


class GenreYear:

    def get_years(self):
        return Movie.objects.filter(draft=False).values_list("year",flat=True).distinct()

    def get_genres(self):
        return Genre.objects.all()


class HomeView(TemplateView):
    template_name = 'myapp/base.html'


class MovieView(GenreYear, ListView):
    """Movie list"""
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = 'myapp/movie_list.html'
    paginate_by = 4


class MovieDetailView(DetailView):
    """ Movie description"""
    model = Movie
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RattingForm()
        context["form"] = ReviewForm()
        return context


class AddReview(View):

    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())


class ActorDetailView(DetailView):
    #Actor information

    model = Actor
    template_name = 'myapp/actor.html'
    slug_field = "url"


class FilterMoviesView(GenreYear, ListView):

    # Aici se vor selecta filmele dupa an sau dupa gen, dar nu dupa an si dupa gen :)
    paginate_by = 4

    def get_queryset(self):

        queryset = Movie.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genres__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args,**kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context


class Search(ListView):

    paginate_by = 3

    def get_queryset(self):
        return Movie.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get('q')
        return context

templates/myapp/actor.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ actor.name }} {% endblock title %}
{% block content%}
    <div class="container">
    <div class="row mt-2 justify-content-md-left">
        <div class="card col-md-auto border-0" style="height: 500px; border:none;">
                <img src="{{ actor.img.url }}" alt="" class="img-fluid card-img-top">
        </div>
        <div class="col-md-4">
            <h3 class=" text-uppercase mt-1"><strong>{{ actor.name }}</strong></h3>
            <dl class="row">
              <dt class="col-sm-4">Date of birth</dt>
              <dd class="col-sm-4">{{ actor.birth }}</dd>
             </dl>
            <h6>{{ actor.description }}</h6>
        </div>
    </div>
    <h2 class="text-primary mt-1 text-center">Actor</h2>
        <hr>
         <div class="row">
            {% for movie in actor.film_actor.all %}
                <div class="col-sm-3 col-md-3">
          <div class="card p-0">
              <div class="card-image"> <img src="{{ movie.poster.url }}" alt=""> </div>
              <div class="card-content d-flex flex-column align-items-center">
                  <h4 class="pt-2"><a href="{{movie.get_absolute_url}}">
                      {{movie.title}}
                  </a></h4>
                  <h5>{{movie.year}}</h5>
                  <ul class="social-icons d-flex justify-content-center">
                      <li style="--i:1">  <span class="fa fa-imdb fa-2x"> </span>: 7.5</li>

                  </ul>
              </div>
          </div>
      </div>
            {% endfor %}
         </div>

    <h2 class="text-primary mt-1 text-center">Director</h2>
    <hr>
     <div class="row">
        {% for movie in actor.film_director.all %}
            <div class="col-sm-3 col-md-3">
      <div class="card p-0">
          <div class="card-image"> <img src="{{ movie.poster.url }}" alt=""> </div>
          <div class="card-content d-flex flex-column align-items-center">
              <h4 class="pt-2"><a href="{{movie.get_absolute_url}}">
                  {{movie.title}}
              </a></h4>
              <h5>{{movie.year}}</h5>
              <ul class="social-icons d-flex justify-content-center">
                  <li style="--i:1">  <span class="fa fa-imdb fa-2x"> </span>: 7.5</li>

              </ul>
          </div>
      </div>
  </div>
        {% endfor %}
     </div>
    </div>
{% endblock content %}

templates/myapp/base.html
{% extends 'base.html' %}
{% load movie_tag %}
{% block content %}
{% get_last_movies %}
{% endblock content%}

templates/myapp/movie_detail.html
{%extends 'base.html'%}
{% block title %} {{ movie.title }} {% endblock title %}
{% block content %}
{% load static %}

    <link href="{% static 'css/rating.css' %}" rel="stylesheet" >
    <link href="{% static 'css/detail_carousel.css' %}" rel="stylesheet" >
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <div class="container">
        <div class="row mt-2 justify-content-md-left">
            <div class=" card  col-md-auto border-0" style="max-height: none">
                <img class="img-fluid card-img-top" src="{{ movie.poster.url }}" alt="" style="height: 500px; border:none;">
            <div class="card-title ">
                <div class="rating">
                    <div class="rating_body">
                        <div class="rating_active"></div>
                            <div class="rating_items">
                                <input type="radio" class="rating_item" value="1" name="rating">
                                <input type="radio" class="rating_item" value="2" name="rating">
                                <input type="radio" class="rating_item" value="3" name="rating">
                                <input type="radio" class="rating_item" value="4" name="rating">
                                <input type="radio" class="rating_item" value="5" name="rating">
                                <input type="radio" class="rating_item" value="6" name="rating">
                                <input type="radio" class="rating_item" value="7" name="rating">
                                <input type="radio" class="rating_item" value="8" name="rating">
                                <input type="radio" class="rating_item" value="9" name="rating">
                                <input type="radio" class="rating_item" value="10" name="rating">
                            </div>
                        </div>

                    <div class="rating_value">
                        3.6
                    </div>
                </div>

            </div>
            </div>
            <div class="col-md-auto">
                <table class="table-borderless">
                    <tbody class="px-1">
                    <h3 class=" text-uppercase mt-1"><strong>{{ movie.title }}</strong></h3>
                        <tr>
                            <th scope="row">Year:</th>
                            <td>{{ movie.year }}</td>
                        </tr>

                        <tr>
                            <th scope="row">Country:</th>

                            <td><a href="">{{ movie.country }}</a></td>
                        </tr>

                        <tr>
                            <th scope="row">Tagline:</th>
                            <td>{{ movie.tagline}}</td>
                        </tr>

                        <tr>
                            <th scope="row">Genres:</th>
                            <td>
                                {% for genre in  movie.genres.all%}
                                    <a href="" >
                                    {{ genre.name }}{% if not forloop.last %}, {% endif %}
                                    </a>
                                {% endfor %}
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">Directors:</th>
                            <td>
                                {% for director in  movie.directors.all%}
                                <a href="{{director.get_absolute_url}}" >
                                    {{ director.name }}{% if not forloop.last %}, {% endif %}
                                </a>
                                {% endfor %}
                            </td>
                        </tr>

                        <tr>
                            <th scope="row">Actors:</th>
                            <td>

                                {% for actor in  movie.actors.all%}
                                <a href="{{actor.get_absolute_url}}" >
                                {{actor.name}}{% if not forloop.last %}, {% endif %}
                                </a>
                                {% endfor %}
                            </td>
                        </tr>


                        <tr>
                            <th scope="row">Premiere</th>
                            <td>{{ movie.world_premiere }}</td>
                        </tr>

                        <tr>
                            <th scope="row">Budget</th>
                            <td>{{ movie.budget }} $</td>
                        </tr>

                        <tr>
                            <th scope="row">Fees in USA</th>
                            <td>{{ movie.fees_in_usa }} $</td>
                        </tr>

                        <tr>
                            <th scope="row">Fees in world</th>
                            <td>{{ movie.fees_in_world }} $</td>
                        </tr>

                        <tr>
                            <th scope="row">iMDb Rating</th>
                            <td>{{ movie.imdb_ratting }}</td>
                        </tr>

                        <tr>
                            <th>
                                  <div class="social-links social-icons">
                                      <a href="#"><i class="fa fa-facebook"></i></a>
                                      <a href="#"><i class="fa fa-twitter"></i></a>
                                      <a href="#"><i class="fa fa-linkedin"></i></a>
                                      <a href="#"><i class="fa fa-github"></i></a>
                                  </div>
                            </th>
                        </tr>

                    </tbody>

                </table>
            </div>
            <h5 class="display-5 text-center"> Story line</h5>
               <p class="align-self-end">
            {{ movie.description|safe }}
        </p>
        </div>

        <h5 class="display-5 text-center"> Movie shots</h5>
         <div class="items">
             {% for image in movie.movieshots_set.all %}
            <div><img src="{{ image.image.url }}" class="img-fluid"></div>
            {% endfor %}
        </div>
        <h5 class="display-5 text-center"> Trailer</h5>
        <div class="ratio ratio-16x9">
            <iframe
              src="{{ movie.trailer}}"
              title="YouTube video"
              allowfullscreen
            ></iframe>
          </div>

        <div class="be-comment-block mt-6">

            <h3 class="comments-title">Comments ({{ movie.reviews_set.count }})</h3>
        <form class="form-block" method="post" action="{% url 'add_review' movie.id %}" id="formReview">
                {% csrf_token %}
                <div class="row">
                    <input type="hidden" name="parent" id="contact-parent" value="">
                    <div class="col-xs-12 col-sm-6 mb-2">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-user" ></i></span>
                            {{ form.name }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 mb-2">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-envelope-o"></i></span>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="form-group">
                            {{ form.text }}
                        </div>
                    </div>
                    {{ form.captcha }}
                    <button class="btn btn-primary pull-right" type="submit">submit</button>
                </div>
            </form>
            {% for review in movie.get_review %}

            <div class="row justify-content-md-left">
                <div class="col-md-auto mt-3" style="display: inline-flex; align-items: center;">
                <a href="javascript:;" class="avatar avatar-lg rounded-circle">
                        <img alt="Image placeholder" src="{% static 'img/team-2.jpg' %}">
                </a>
                           <h5 class="name ps-3">
                        {{ review.name }}
                            </h5>
                                 <span class="mx-2">
                                     <small>
                            <i class="fa fa-clock-o"></i>
                        {{ review.date }}
                                         </small>
                    </span>
                </div>
                    </div>

                    <div class="card card-frame" style="max-height: 100%; max-width: 60%">
                        <p class="px-3 text-md-left">{{ review.text }}</p>
                        <span class="text-gradient text-primary text-uppercase text-xs font-weight-bold my-2 mx-2 align-self-end">
                            <a href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')"><i class="ni ni-chat-round"></i> Reply</a>
                        </span>
                    </div>
                {% for rew in review.reviews_set.all %}
                <div class="row justify-content-md-center">
                <div class="col-md-auto mt-3 d-flex">
                <a href="javascript:" class="avatar avatar-lg rounded-circle">
                        <img alt="Image placeholder" src="{% static 'img/team-2.jpg' %}">
                </a>
                           <h5 class="name ps-3">
                        {{ rew.name }}
                            </h5>
                                 <span class="mx-2">
                                     <small>
                            <i class="fa fa-clock-o"></i>
                        {{ rew.date }}
                                         </small>
                    </span>

                </div>

                    </div>
                <div class="row justify-content-md-end">
                <div class="card card-frame align-items-lg-end" style="max-height: 100%; max-width: 60%;">
                        <p class="px-3 text-md-left">{{ rew.text }}</p>
                    </div>
                </div>
                {% endfor %}
            {% endfor %}


        </div>
    </div>
    <script>
    function addReview(name, id) {
        document.getElementById("contact-parent").value = id;
        document.getElementById("contact-comment").innerText = `${name}, `


    }
    </script>
    <script src="{% static 'js/carousel.js' %}"></script>
    <script src="{% static 'js/rating.js' %}"></script>

{% endblock %}

templates/myapp/movie_list.html
{% extends 'myapp/base.html' %}

{% block content%}
    <div class="row">
        <div class="wrapper col-md-9">
            <div class="container ms-lg-3">
            <h2 class="text-primary mt-2 text-center">Movies</h2>
            <hr>
            <div class="container">
              <div class="row">
                  {% for movie in movie_list %}
                  <div class="col-sm-3 col-md-3">
                      <div class="card p-0">
                          <div class="card-image"> <img src="{{ movie.poster.url }}" alt=""> </div>
                          <div class="card-content d-flex flex-column align-items-center">
                              <h4 class="pt-2"><a href="{{movie.get_absolute_url}}">
                                  {{movie.title}}
                              </a></h4>
                              <h5>{{movie.country}}</h5>
                              <ul class="social-icons d-flex justify-content-center">
                                  <li style="--i:1">  <span class="fa fa-imdb fa-2x"> </span>: 7.5</li>

                              </ul>
                          </div>
                      </div>
                  </div>
                  {% endfor %}
              </div>
          </div>
          <hr>
            {% include 'include/pagination.html' %}
          </div>
        </div>

 {% include 'include/filter.html' %}

{% endblock %}